#!/bin/bash
#
# Regenerates the responsive images in public/images/ from the originals.
#
# Usage:  SRC=/path/to/originals ./scripts/optimize-images.sh
#
# Each source is exported as JPEG at several widths; the data files in
# src/data/ list which widths exist per image so `srcSet` stays accurate.
# Uses macOS `sips`, so no image tooling needs installing.
#
# NOTE: two originals were cropped by hand before export and are NOT
# regenerated by this script — re-cropping would undo the fix:
#   * "Okra Soup with Asorted"   — removed the CamScanner page border/watermark
#   * "Spaghetti Jollof …"       — removed a cut-off text banner and padding
#
set -euo pipefail
SRC="${SRC:-$HOME/Desktop/Dilly Kitchen}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/public/images"
Q=68

mkdir -p "$OUT/brand" "$OUT/hero" "$OUT/story" "$OUT/dishes" "$OUT/catering"

# usage: emit <srcfile> <destdir> <slug> <w1> <w2> ...
emit() {
  local src="$1"; local dir="$2"; local slug="$3"; shift 3
  local srcw
  srcw=$(sips -g pixelWidth "$src" | awk '/pixelWidth/{print $2}')
  for w in "$@"; do
    if [ "$w" -gt "$srcw" ]; then continue; fi
    sips -s format jpeg -s formatOptions "$Q" --resampleWidth "$w" "$src" --out "$dir/$slug-$w.jpg" >/dev/null 2>&1
  done
}

echo "-- brand"
emit "$SRC/Logo.jpeg"                              "$OUT/brand"    "dilly-kitchen-logo" 512 256 128
echo "-- hero"
emit "$SRC/Smoky Jollof Rice.jpeg"                  "$OUT/hero"     "jollof-rice-hero" 720 480
emit "$SRC/Hero Page Picture.jpeg"                 "$OUT/hero"     "restaurant-interior" 1440 960 640
echo "-- story"
emit "$SRC/Our Story Picture .jpeg"                "$OUT/story"    "chef-portrait" 1000 700 480
emit "$SRC/Chelf hand.jpeg"                        "$OUT/story"    "chef-plating" 1100 760 500
echo "-- catering"
emit "$SRC/Birthday Party Package for Client.jpeg" "$OUT/catering" "birthday-package" 720 480
echo "-- dishes"
emit "$SRC/Gallery/Beef Suya .jpeg"                                 "$OUT/dishes" "beef-suya"            1400 800 480
emit "$SRC/Gallery/Fried Plaintan.jpeg"                             "$OUT/dishes" "fried-plantain"       1400 800 480
emit "$SRC/Gallery/Fried Yam.jpeg"                                  "$OUT/dishes" "fried-yam"            1400 800 480
emit "$SRC/Gallery/Grilled crocker Fish with Fried Plaintain.jpeg"  "$OUT/dishes" "grilled-croaker-fish" 1400 800 480
emit "$SRC/Gallery/Grilled Fish with Prawns.png"                     "$OUT/dishes" "grilled-fish-prawns"  1080 800 480
emit "$SRC/Gallery/Jollof with Chicken.jpeg"                        "$OUT/dishes" "jollof-rice-chicken"  1400 800 480
emit "$SRC/Gallery/Meat Pie.jpeg"                                   "$OUT/dishes" "meat-pie"             1400 800 480
emit "$SRC/Gallery/Isi-Ewu .jpeg"                                   "$OUT/dishes" "isi-ewu"              1400 800 480
emit "$SRC/Gallery/Puff Puff.jpeg"                                  "$OUT/dishes" "puff-puff"            1400 800 480
emit "$SRC/Gallery/Ried Rice with Protein & Plaintan.jpeg"          "$OUT/dishes" "fried-rice"           1400 800 480
emit "$SRC/Gallery/Tilapia Pepper Soup .jpeg"                       "$OUT/dishes" "tilapia-pepper-soup"  1400 800 480
emit "$SRC/Gallery/White Rice & Stew & Plaintain.jpeg"              "$OUT/dishes" "white-rice-stew"      1400 800 480
emit "$SRC/Gallery/Efo Riro.png"                                    "$OUT/dishes" "efo-riro"             1400 800 480

echo "-- done"
